### ISSUE TITLE
Incorrect cfi?

### ISSUE THREAD

**Issue by larsvoigt** [larsvoigt/epub-full-text-search#10]
``` xml
<p><span class="exercisenumber"><em>1</em></span> 
Prüfen Sie ehrlich und selbstkritisch Ihre Stärken und Schwächen in den Lern- und
Arbeitstechniken.
</p>
```
Looking for keyword: *Lern*. What is the  correct cfi inline path?
```
,/3:87,/3:91
or
,/2:87,/2:91
```

**Comment by danielweck** [comment]
http://www.idpf.org/epub/linking/cfi/epub-cfi.html#sec-path-child-ref

[XML] character data that is interspersed amongst sibling child elements (i.e., "mixed content" context) is logically organised into (potentially-empty) chunks of contiguous character data: the first chunk is located before the first child element (left sibling), the last chunk is located after the last child element (right sibling), and there is one chunk between each pair of child elements. When there are no child elements, there is one (potentially-empty) chunk of character data. Consecutive (potentially-empty) chunks of character data are each assigned odd indices (i.e., starting at 1, followed by 3, etc.).

**Comment by danielweck** [comment]
So, `3` is the correct text chunk index.
(`1` is the empty one between `p` and `span`)

**Comment by larsvoigt** [comment]
Thank you @danielweck for the explanation. Helps me 	enormous.
