### ISSUE TITLE
issues in updated version

### ISSUE THREAD

**Issue by hajarghaem** [larsvoigt/epub-full-text-search#25]
Hi @larsvoigt,
1- where does the indexed files saved?
In the previouse version I could see that the indexed files has a name "IndexControllerDB". But after updating the new version I cannot find such file. Could you please let me know how to do you save indexed files? 
2- How does it look for a book? (with its tile or file name?)
Another issues is that with the new version it looks for the title of the book and not the name of the book folder? I have integrated epub-search in Readium and with the previous version it worked without such issues!

Thanks in advance,
Hajar

**Comment by larsvoigt** [comment]
Hi @hajarghaem,
apologize that are undocumented changes: 

1 - Now the application data are stored in ```~/.epub-full-text-search``` (Linux) in the HOME directory of the user.  

2- It look for a specific book via title form ```package.opf``` → ```package/metadata/dc:title```.  Use this internally to this distinguish the books. I had to change the internal representation: now it removes all whitespace from ```title``` string. Unfortunately do you have to reindex your epub collection and than it should works fine again. 

Best 
Lars

**Comment by hajarghaem** [comment]
Hi @larsvoigt,
Thanks for your time and information.

For number 1, I do not get the answer. Actually I am looking for a file that you save the data of indexed ebooks.
**I even re indexed my epooks but I did not find any place/file that holds these data! In the previous version it as saved in "IndexControllerDB".**

Could you please let me know **where(which file) do you save the information of indexed books in the new version**?

Thanks in advance,
Hajar

**Comment by larsvoigt** [comment]
Hi @hajarghaem,
```IndexControllerDB.json```  and other applcation data should be found here ```cd ~/.epub-full-text-search``` ? 
Lars

**Comment by hajarghaem** [comment]
Hi @larsvoigt 
I used npm install epub-full-text-search -g (https://www.npmjs.com/package/epub-full-text-search)
so I have my epub-search in
AppData\Roaming\npm\node_modules\epub-full-text-search

And there is no IndexControllerDB.json in there, even not in my computer!
I need to access to it in order to read and compare book names/title (the one that is shown in readium and the one you use in epub-search).

**Could you please let me know in what libray or code (epub-full-text-search\src? or epub-full-text-search\node_modules?) of epub-search you save this file with IndexControllerDB.json  as its name?**

**Comment by larsvoigt** [comment]
Ohh dear windows! :-). ```%userprofile%/.epub-full-text-search```

**Comment by hajarghaem** [comment]
Hi @larsvoigt,
Right!!! But it is strange that windows could not find it by search!!!
Thanks for the hint.
